-- liquibase formatted sql

-- changeset janek:1689412646831-1
CREATE TABLE "event" ("event_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "date" TIMESTAMP WITHOUT TIME ZONE, "description" VARCHAR(255), "type" SMALLINT, "name" VARCHAR(255), "owner_id" INTEGER, CONSTRAINT "event_pkey" PRIMARY KEY ("event_id"));

-- changeset janek:1689412646831-2
CREATE TABLE "eventmodules" ("module_type" VARCHAR(31) NOT NULL, "eventmodule_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "event_id" INTEGER, CONSTRAINT "eventmodules_pkey" PRIMARY KEY ("eventmodule_id"));

-- changeset janek:1689412646831-3
CREATE TABLE "usr" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255), "name" VARCHAR(255), "surname" VARCHAR(255), CONSTRAINT "usr_pkey" PRIMARY KEY ("id"));

-- changeset janek:1689412646831-4
CREATE TABLE "event_event_modules" ("event_event_id" INTEGER NOT NULL, "event_modules_eventmodule_id" INTEGER NOT NULL);

-- changeset janek:1689412646831-5
CREATE TABLE "event_participants" ("event_id" INTEGER NOT NULL, "user_id" INTEGER NOT NULL);

-- changeset janek:1689412646831-6
ALTER TABLE "event" ADD CONSTRAINT "fk4s9dbitss89g801yg5xfkh43i" FOREIGN KEY ("owner_id") REFERENCES "usr" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset janek:1689412646831-7
ALTER TABLE "event_participants" ADD CONSTRAINT "fk5232w1ta0icpkemgsxyw8a976" FOREIGN KEY ("event_id") REFERENCES "event" ("event_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset janek:1689412646831-8
ALTER TABLE "event_event_modules" ADD CONSTRAINT "fkfo4jg9raik1iovynovhum1pmn" FOREIGN KEY ("event_modules_eventmodule_id") REFERENCES "eventmodules" ("eventmodule_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset janek:1689412646831-9
ALTER TABLE "event_participants" ADD CONSTRAINT "fkidt99ub8o1798gcnpv9r8c46" FOREIGN KEY ("user_id") REFERENCES "usr" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset janek:1689412646831-10
ALTER TABLE "event_event_modules" ADD CONSTRAINT "fkkpel54bhe10kqmaxe6t2xn8yt" FOREIGN KEY ("event_event_id") REFERENCES "event" ("event_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset janek:1689412646831-11
ALTER TABLE "eventmodules" ADD CONSTRAINT "fksuyynu5kw9y238upd44o533oj" FOREIGN KEY ("event_id") REFERENCES "event" ("event_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

